### ISSUE TITLE
Cant download mods from the browser

### ISSUE THREAD

**Issue by xxcoopersacid** [bluemagic123/tModLoader#2146]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I cant download mods, every time I try to download one the progress bar shows up then disappears.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8054963/client.log)

### Steps to reproduce

1. Open Mod browser
2. Try to download a mod

### Expected Behavior

The progress bar fills up then the mod downloads to your "Mods" folder

### Actual Behavior

The progress bar doesn't go up and disappears almost instantly

### Reproduction frequency

Everytime I try the issue occurs

**Comment by LennyPhoenix** [comment]
This occurs for me too on linux

**Comment by BlizardTerrain** [comment]
The same issue seems to also occur on macs running on the m1 chips, i don't know if intel chips also have the same issue

**Comment by Rijam** [comment]
There is an issue with select mods being undownloadable. You can manually download mods from these sources:

Mod Browser Mirror: https://mirror.sgkoi.dev/
DirectModDownloadListing: http://javid.ddns.net/tModLoader/DirectModDownloadListing.php (Use Ctrl + F to search for the mod you want)
The mod's GitHub page (if applicable)

Don't know how to manually download mods? Follow this guide: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#Installing-Mods

**Comment by JavidPack** [comment]
This is fixed in the latest.

**Comment by thennothinghappened** [comment]
This is still broken, I just installed tmodloader from Steam and I have the same issue. I also tried using the 1.3 beta from the dropdown but that instantly crashes the game, and I had to re-install to fix it.

**Comment by JavidPack** [comment]
This particular error mentioned in the log is fixed, if you have a different issue that is not covered in the existing open issues and can't be solved by asking for support in the discord, then that might be a separate issue. The first source of support is the discord.
