### ISSUE TITLE
Crashes on Linux "Failed to load asset"

### ISSUE THREAD

**Issue by johanbluecreek** [bluemagic123/tModLoader#2377]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Some assets appear to fail to load causing crashes on Linux. This includes killing a Snow Flinx which causes a Failed to load of a Gore asset (can be circumvented by disabling gore and blood in the settings) and when placing or destroying a Slush block there is a Failed to load of a Projectile asset.

### Log File

There is no client.log on my system. `~/.local/share/Terraria/ModLoader/Logs/` does not exist, `$XDG_DATA_HOME` is not defined, and `find ~/ -name client.log` returns nothing.

### Steps to reproduce

1. Go to Snow Biome
2. Find Snow Flinx or Slush Block
3.a Kill Snow Flinx -> Crash
3.b Mine Slush Block -> Crash

### Expected Behavior

Crash should not occur.

### Actual Behavior

Crashes when failing to load assets.

### Reproduction frequency

Triggered Snow Flings missing asset bug 4/4 times, and triggered Slush Block bug 3/3 times.

### Additional Information

I tried verifying integrity of files, this did not help. All mods were disabled and the bug does not happen in plain Terraria. This is the type of error message I get when the game crashes (this is from the Slush Block):
![screenshot-20220512@160455](https://user-images.githubusercontent.com/852554/168100643-5a66f205-3b89-4ba6-914f-815aece8a499.png)
The game is hosted from a Windows computer whose player does not experience the same issues.

**Comment by johanbluecreek** [comment]
I noticed that issue #2037 had a similar problem, then it was a Terraria version mismatch causing a problem on Windows, it appears. Just wanted to mention that I run Terraria v1.4.3.6 and tModLoader v2022.4.62.6 (stable-1.4) both installed via Steam.

**Comment by direwolf420** [comment]
That linked issue was due to that particular terraria version adding new textues, which tml needed but didnt find since the user didnt update terraria. Your issue is different:
I am not sure how accurate this listing is, but basically some vanilla assets have the wrong capitalization:
```
fade-out.xnb
gemChain-2.xnb
gore_240.xnb
jellyfishBowl1.xnb
jellyfishBowl2.xnb
jellyfishBowl3.xnb
logo_1.xnb
logo_2.xnb
logo_3.xnb
logo_4.xnb
logo_5.xnb
logo_6.xnb
logo_7.xnb
logo_8.xnb
projectile_179.xnb
projectile_618.xnb
```
Check if any of these are lowercase, and change their case, you find them in the game files (`~/.local/share/Steam/steamapps/common/Terraria/Content/Images`), maybe check tModLoader too.

**Comment by johanbluecreek** [comment]
On some of them it is fairly straight forward to figure out the capitalization, but for
```
fade-out.xnb
jellyfishBowl[123].xnb
```
I guess it is just the first letter that is capitalized?

I also found `npc_517.xnb` that probably also should be all caps just like the rest of the similar files.

When you say I should be checking tModLoader too, which files/folders do you mean? In `~/.local/share/Steam/steamapps/common/tModLoader/` there are no `xnb`-files.

**Comment by direwolf420** [comment]
`~/.local/share/Steam/steamapps/common/tModLoader/Content/Images`
Don't know about the first two you mentioned, if they dont throw errors leave them as is.

**Comment by johanbluecreek** [comment]
And the files `logo_[1-8].xnb` are apparently in correct case and should not be renamed. Game crashes at main menu when those are renamed.

**Comment by johanbluecreek** [comment]
> `~/.local/share/Steam/steamapps/common/tModLoader/Content/Images`

That folder does not exist.

> Don't know about the first two you mentioned, if they dont throw errors leave them as is.

Those files should not be capitalized either apparently.

**Comment by johanbluecreek** [comment]
To to make it a bit clearer, by renaming the following files in `~/.local/share/Steam/steamapps/common/Terraria/Content/Images`
```
gemChain-2.xnb
gore_240.xnb
projectile_179.xnb
projectile_618.xnb
npc_517.xnb
```
to
```
GemChain-2.xnb
Gore_240.xnb
Projectile_179.xnb
Projectile_618.xnb
NPC_517.xnb
```
respectively, the crashes does not longer occur. I guess however I leave this issue open, for the devs to determine how they want this issue to be solved.

**Comment by JavidPack** [comment]
I believe we fixed this in e605b8e3aa70e6b3117766e56660c5197d783eb3

**Comment by direwolf420** [comment]
The fix was only for windows. It still happens to linux, rarely seen in tml discords support channel

**Comment by azzzertyy** [comment]
Can confirm this occurs as of v2022.9.47.47 on linux.

**Comment by JasonLandbridge** [comment]
Still indeed an issue for Linux users

**Comment by Adrianinoninja** [comment]
low key this is still happening low key low key (atleast for me it did)
