### ISSUE TITLE
May update won't launch on Steam Linux (`Libraries/Newtonsoft.Json` referred to by wrong capitalization in manifest json)

### ISSUE THREAD

**Issue by kode54** [bluemagic123/tModLoader#4190]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

The Steam version of tModLoader won't launch after the May update. The button goes green for a moment, then resets again. A window never opens.

The problem appears to be that the `tModLoader.deps.json` refers to a whole mess of dependencies by paths containing `net6.0` and not the new `net8.0` like they should.

I'm attaching only the relevant logs.

### Log File

[Launch.log](https://github.com/tModLoader/tModLoader/files/15173481/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/15173482/Natives.log)

### Steps to reproduce

1. Update tModLoader to the May patch update on Linux
2. Attempt to launch the game

### Expected Behavior

Game launches normally.

### Actual Behavior

Game doesn't launch.

### Reproduction frequency

Easy to reproduce. The game is currently non-functional on Linux.

**Comment by kode54** [comment]
Upon further inspection, only the `Newtonsoft.json.dll` dependency needs to be changed to `net8.0` in its path. All the rest are still the same.

Edit: Never mind it is supposed to be `net6.0`, but there's an error loading the dep either way.

Edit 2: Oh, son of a gun. This is a capitalization issue. The file is named `Newtonsoft.json.dll` and the manifest specifies `Newtonsoft.Json.dll`, note the capital J in json.

Edit 3: Third time's a charm. The section that declares the Libraries folder name calls it `newtonsoft.json` in all lower case, while the folder is `Newtonsoft.Json`.

**Comment by drunken-dwarf** [comment]
I tested out the changes from Edit 3 by @kode54 and can confirm that tModLoader now launches normally (Ubuntu 22.04.4).

**Changing the folder name Newtonsoft.Json to newtonsoft.json (all lower case) fixes the issue**, as described.

Considering that (most) folders are also all lower case, I suggest changing the folder, not the manifest.

**Comment by ogkush920** [comment]
i can confirm also. tmodloader worked last night. doesnt open this morning after update. and renaming Newtonsoft.Json.dll folder also to all lowerase, tmodloader now opens again

**Comment by JavidPack** [comment]
We've released a couple hotfixes that should resolve this issue, someone with this issue please comment if it is now fixed after testing it once more.

**Comment by EchelonCrusher** [comment]
Hey! I still have the issue. Updated, verified cache, reinstalled but to no avail.

Natives.log:
Error:
  An assembly specified in the application dependencies manifest (tModLoader.deps.json) was not found:
    package: 'Newtonsoft.Json', version: '13.0.3'
    path: 'lib/net6.0/Newtonsoft.Json.dll'

Launch.log:
Logging to /home/<name>/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Fixing Environment Issues
Success!
Verifying .NET....
Parsing .NET version requirements from runtimeconfig.json
Success! dotnet_version=8.0.0
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/home/<name>/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/tModLoader/dotnet"
Attempting Launch...
Launched Using Local Dotnet. Launch command: "/home/<name>/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/tModLoader/dotnet/dotnet" tModLoader.dll ""

**Comment by drunken-dwarf** [comment]
I deleted the (already renamed) newtonsoft.json folder and verified cache. Came back all lowercase and working.
